---
- name: Setup Go environment and application directories
  import_tasks: setup.yml

- name: Build backend application
  import_tasks: build.yml

- name: Deploy backend application and configure service
  import_tasks: deploy.yml