---
- name: Connection Check
  hosts: all
  tasks:
    - name: Ping the server
      ping:

- name: Setup Infrastructure
  hosts: all
  become: yes
  roles:
    # 物理ネットワーク系
    - role: host_network_setup
      tags: [network, host]

    # SSH Gateway
    - role: ssh_gateway
      tags: [ssh]

    # 必要なソフトウェアのインストール
    - role: zfs_setup
      tags: [zfs]
    - role: ovn_setup
      tags: [ovn]
    - role: incus_setup
      tags: [incus]
    - role: nginx_setup
      tags: [nginx]
    - role: sqlite_setup
      tags: [sqlite]
    - role: etcd_setup
      tags: [etcd]
    - role: coredns_setup
      tags: [coredns]

    # ネットワークの構築
    - role: incus_ovn_uplink
      tags: [network, incus, ovn, uplink]
    
    # Resolvedの設定
    - role: systemd_resolved_setup
      tags: [systemd, resolved]

    # BGPの設定
    - role: incus_bgp_speaker
      tags: [bgp, incus]
    - role: frr_server_setup
      tags: [bgp, incus, frr]

    - role: app_backend
      tags: [app, backend]
    - role: app_frontend
      tags: [app, frontend]