---
# Create a user for SSH gateway
- name: Create Jump user
  ansible.builtin.user:
    name: "{{ jump_user_name | default('jumpuser') }}"
    shell: /bin/bash
    create_home: yes
    home: /home/{{ jump_user_name | default('jumpuser') }}