---
# ovn-uplink (physical) の parent となる interface を作る
# gateway として機能させるため IP アドレスを割り当てる
- name: Deploy Netplan config for OVN uplink
  ansible.builtin.template:
    src: 99-ovn-uplink.yml.j2
    dest: /etc/netplan/99-ovn-uplink.yml

- name: Apply Netplan config
  ansible.builtin.command: netplan apply