---
# cf. https://etcd.io/docs/
etcd_version: v3.6.0
# cf. https://etcd.io/docs/v3.6/install/
# バイナリからのインストールが必要（Linuxなら）
etcd_download_url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
etcd_install_dir: "/usr/local/bin"
etcd_data_dir: "/var/lib/etcd"