---
# cf. https://incus-ja.readthedocs.io/ja/latest/howto/network_ovn_setup/#network-ovn-setup
#     https://linuxcontainers.org/incus/docs/main/reference/network_physical/#network-physical
- name: Check if OVN uplink exists
  ansible.builtin.command: "incus network show {{ incus_uplink_bridge_name }}"
  register: bridge_check
  failed_when: false
  changed_when: false

- name: Create shared uplink bridge (physical) for OVN
  ansible.builtin.command:
    cmd: >
      incus network create {{ incus_uplink_bridge_name }}
      --type=physical
      parent={{ ovn_uplink_nic }}
      ipv4.gateway={{ ovn_uplink_ip }}
      ipv4.ovn.ranges={{ incus_ovn_external_range }}
  when: bridge_check.rc != 0

- name: Sync uplink bridge (physical) configurations
  ansible.builtin.command:
    cmd: >
      incus network set {{ incus_uplink_bridge_name }}
      ipv4.ovn.ranges={{ incus_ovn_external_range }}
      ovn.ingress_mode=routed
  changed_when: true
