package user

import (
	"context"
	"errors"

	"example.com/m/internal/domain/network"
	"example.com/m/internal/domain/user"
	"example.com/m/internal/usecase"
	networkUC "example.com/m/internal/usecase/network"
	"github.com/google/uuid"
)

// --- Default Quota ---
const (
	DefaultMaxInstance = 5
	DefaultMaxCPU      = 2
	DefaultMaxMemory   = 2048 // in MB
)

type EnsureUserInput struct {
	Sub string
}

type EnsureUserUseCase interface {
	Execute(ctx context.Context, input EnsureUserInput) (*user.User, error)
}

type ensureUserInteractor struct {
	userRepo     user.UserRepository
	networkRepo  network.Repository
	identitySvc  user.IdentityService
	ipCalculator network.NetworkService
	publisher    usecase.JobPublisher
	uow          usecase.UnitOfWork
}

func NewEnsureUserInteractor(
	userRepo user.UserRepository,
	networkRepo network.Repository,
	identitySvc user.IdentityService,
	ipCalculator network.NetworkService,
	publisher usecase.JobPublisher,
	uow usecase.UnitOfWork,
) EnsureUserUseCase {
	return &ensureUserInteractor{
		userRepo:     userRepo,
		networkRepo:  networkRepo,
		identitySvc:  identitySvc,
		ipCalculator: ipCalculator,
		publisher:    publisher,
		uow:          uow,
	}
}

func (i *ensureUserInteractor) Execute(ctx context.Context, input EnsureUserInput) (*user.User, error) {
	// check existing user
	userData, err := i.userRepo.FindByID(ctx, user.UserID(input.Sub))
	if err != nil && !errors.Is(err, user.ErrUserNotFound) {
		return nil, err
	}
	if userData != nil {
		// if exist, return user information
		identity, err := i.identitySvc.GetIdentity(ctx, input.Sub)
		if err != nil {
			return nil, err
		}
		usr := user.NewUser(
			user.UserID(input.Sub),
			identity.DisplayName,
			identity.Permissions,
			userData.Quota,
			userData.Status,
			userData.ErrorPhase,
		)
		return usr, nil
	}

	// if not exist, create new user
	// create user in database( only persist id and quote )
	// NOTE: Temporary, quote is generated by const value.
	var newUser *user.User
	var vpcID network.VPCID
	var subnetID network.SubnetID
	err = i.uow.Do(ctx, func(ctx context.Context) error {
		pUser := &user.UserPersistentData{
			ID: user.UserID(input.Sub),
			Quota: user.UsageQuota{
				MaxInstance: DefaultMaxInstance,
				MaxCPU:      DefaultMaxCPU,
				MaxMemory:   DefaultMaxMemory,
			},
			Status: user.UserStatusPending, // At first, set status to pending
			// FailedPhase is nil at first.
		}
		identity, err := i.identitySvc.GetIdentity(ctx, input.Sub)
		if err != nil {
			return err
		}
		newUser := user.NewUser(
			user.UserID(input.Sub),
			identity.DisplayName,
			identity.Permissions,
			pUser.Quota,
			pUser.Status,
			pUser.ErrorPhase,
		)
		if err := i.userRepo.Save(ctx, newUser); err != nil {
			return err
		}

		// save VPC information to repository
		vpcID = network.VPCID("vpc-" + uuid.New().String())
		usedVPCCIDR, err := i.networkRepo.ListAllUsedCIDRs(ctx)
		if err != nil {
			return err
		}
		vpcCidr, err := i.ipCalculator.CalculateNextAvailableVPCCIDR(ctx, usedVPCCIDR)
		if err != nil {
			return err
		}
		vpc := network.NewVPC(vpcID, string(newUser.ID()), "vpc-default", vpcCidr)
		if err := i.networkRepo.SaveVPC(ctx, vpc); err != nil {
			return err
		}

		// save Subnet information to repository
		subnetID = network.SubnetID("subnet-" + uuid.New().String())
		// NOTE: Temporary, usedIPs is empty because subnet is not created yet.
		subnetCidr, err := i.ipCalculator.CalculateNextAvailableSubnet(ctx, vpcCidr, []string{})
		if err != nil {
			return err
		}
		subnet := network.NewSubnet(subnetID, vpcID, "subnet-default", subnetCidr)
		if err := i.networkRepo.SaveSubnet(ctx, subnet); err != nil {
			return err
		}
		return nil
	})

	// create JOB to create VPC and Subnet
	payload := networkUC.CreateVPCAndDefaultSubnetPayload{
		VPCID:    vpcID,
		SubnetID: subnetID,
	}
	if err := i.publisher.Publish(ctx, usecase.JobTypeCreateVPCAndDefaultSubnet, payload); err != nil {
		newUser.MarkAsFailed(user.FailedInPending) // ジョブのキューイングに失敗した場合はfailed状態にする
		_ = i.userRepo.Save(ctx, newUser)           // エラー状態を保存
		return nil, err
	}

	newUser.MarkAsInitializing() // ジョブ実行中はinitializing状態にする
	if err := i.userRepo.Save(ctx, newUser); err != nil {
		newUser.MarkAsFailed(user.FailedInPending)
		_ = i.userRepo.Save(ctx, newUser)
		return nil, err
	}
	return newUser, nil
}
