---
- name: Get OVN NB DB socket path from config
  ansible.builtin.shell: |
    grep -oP '(?<=--db-nb-socket=)[^ ]+' /etc/default/ovn-central
  register: ovn_nb_socket_path
  changed_when: false

- name: Link Incus to OVN Northbound DB
  ansible.builtin.command:
    cmd: incus config set network.ovn.northbound_connection {{ ovn_nb_socket_path.stdout }}