---
# cf. https://incus-ja.readthedocs.io/ja/latest/howto/network_ovn_setup/#network-ovn-setup
- name: Check if uplink bridge exists
  ansible.builtin.command: incus network show {{ incus_uplink_bridge_name }}
  register: bridge_check
  failed_when: false
  changed_when: false

- name: Create shared uplink bridge for OVN
  ansible.builtin.command:
    cmd: >
      incus network create {{ incus_uplink_bridge_name }}
      ipv4.address={{ incus_uplink_bridge_cidr }}
      ipv4.nat=true
      dns.mode=managed
  when: bridge_check.rc != 0

- name: Configure IP ranges for OVN subnets
  ansible.builtin.command:
    cmd: >
      incus network set {{ incus_uplink_bridge_name }}
      ipv4.dhcp.ranges={{ incus_ovn_dhcp_range }}
      ipv4.ovn.ranges={{ incus_ovn_external_range }}
  changed_when: true

- name: Set bridge as OVN uplink
  ansible.builtin.command:
    cmd: incus network set {{ incus_uplink_bridge_name }} ovn.ingress_mode=proxy
  changed_when: false